# root
[workspace]
resolver = "2"
members = [
    "dsh-api",
    "dsh-api-generated"
]

[workspace.package]
authors = ["Unibox Team <unibox@kpn.com>"]
edition = "2021"
publish = ["artifactory"]
rust-version = "1.77"
version = "0.2.0"
