[workspace]
resolver = "2"
members = [
    "dcli",
    "dsh_api",
    "engine",
]

[workspace.package]
authors = ["Wilbert Schelvis <wilbert.schelvis@kpn.com"]
description = "Business logic for Trifonius project"
edition = "2021"
rust-version = "1.77"
version = "0.0.7"
publish = ["artifactory"]
