fn_params_layout = "Tall"
format_code_in_doc_comments = true
#group_imports = "StdExternalCrate"
imports_layout = "Mixed"

fn_call_width = 100

use_field_init_shorthand = true

max_width = 180
use_small_heuristics = "Max"
wrap_comments = false
comment_width = 100

tab_spaces = 2
indent_style = "Block"
empty_item_single_line = true

overflow_delimited_expr = true

chain_width = 100
