[package]
name = "trifonius-engine"

authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
dsh_rest_api_client = "0.1.0"
dsh_sdk = { version = "0.4.2", features = ["rest-token-fetcher"], default-features = false }

futures = "0.3.30"
lazy_static = "1.5.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
toml = "0.8.14"
urlencoding = "2.1.3"
num-traits = "0.2.19"
