# dsh-api-build
[package]
publish = false
name = "dsh_api_build"

[dependencies]
indoc = "2.0"
openapiv3 = "2"
prettyplease = "0.1"
progenitor = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
syn = "1"
